channels:
  - r
  - conda-forge
dependencies:
  - matplotlib
  - python>=3
  - sphinx>=1.6
  - pandoc
  - nbconvert!=5.4
  - ipykernel
  - xlrd
  - numpy
  - pandas
  - pip:
    - nbsphinx
    - sphinx_rtd_theme
